### ISSUE TITLE
Resources don't work with wasmtime backend

### ISSUE THREAD

**Issue by olliptln** [DouglasDwyer/wasm_component_layer#6]
The resource example doesn't work with wasmtime backend, although it works with wasmi backend. 

I changed the following line in the beginning of examples/resource.rs:
let engine = Engine::new(wasmi::Engine::default());
to:
let engine = Engine::new(wasmtime::Engine::default());

Running the example with "cargo run --example resource" gives the following error:

thread 'main' panicked at examples/resource.rs:90:53:
called `Result::unwrap()` on an `Err` value: in test:guest/foo.use-resource: error while executing at wasm backtrace:
    0:  0x283 - resource::test::guest::bar::Myresource::new::h729c8f371c20bbf5
                    at /home/user/Downloads/wasm_component_layer-master/examples/resource/src/lib.rs:1:1
    1:  0x4ca - <resource::Foo as resource::exports::test::guest::foo::Foo>::use_resource::h0af7dd4b4b71497d
                    at /home/user/Downloads/wasm_component_layer-master/examples/resource/src/lib.rs:13:24
    2:  0x524 - test:guest/foo#use-resource
                    at /home/user/Downloads/wasm_component_layer-master/examples/resource/src/lib.rs:1:1

Caused by:
    0: error while executing at wasm backtrace:
           0:  0x283 - resource::test::guest::bar::Myresource::new::h729c8f371c20bbf5
                           at /home/user/Downloads/wasm_component_layer-master/examples/resource/src/lib.rs:1:1
           1:  0x4ca - <resource::Foo as resource::exports::test::guest::foo::Foo>::use_resource::h0af7dd4b4b71497d
                           at /home/user/Downloads/wasm_component_layer-master/examples/resource/src/lib.rs:13:24
           2:  0x524 - test:guest/foo#use-resource
                           at /home/user/Downloads/wasm_component_layer-master/examples/resource/src/lib.rs:1:1
    1: Unable to convert ExternRef(None) to component type.

This comes from the last line of resource.rs:
use_resource.call(&mut store, ()).unwrap();
where call returns the Err.

The single_component example works with a similar change of the engine to wasmtime, which suggests that wasmtime is set up correctly, but resources specifically don't work with it.

**Comment by DouglasDwyer** [comment]
Fixed in commit 89f9ddf69449a3cd97f30d5e719be76543d451ff and release `0.1.14`. Please reopen if the issue persists!
